[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.6",
    "flask>=3.1.2",
    "flask-socketio>=5.5.1",
    "requests>=2.32.5",
]
